### ISSUE TITLE
Not possible to change room settings when creating a room

### ISSUE THREAD

**Issue by tibroc** [THM-Health/PILOS#1101]
**Describe the bug**
When creating a room it is not possible to change the room settings

**To Reproduce**
1. Go to 'Räume'
2. Click on 'Raum erstellen'
3. Go to 'Standard Raumeinstellungen'
4. Try to toggle any setting.

**Expected behavior**
The settings change when clicking on the toggle buttons. However, they don't.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Chromium

**Comment by SamuelWei** [comment]
This list only shows you the default options of this room type, they cannot be changed during the creating of a room.
As soon as the room has been created these settings are applied. Some of the settings can be always be changed, others can only be changed if the user enabled the expert mode and enforced settings can never be changed. This list should give the user a detailed overview that the selected room type is.

**Comment by SamuelWei** [comment]
@tibroc  Did this answer your question? If so please close the issue. If not, please let me know what we could do better from your point of view.

**Comment by tibroc** [comment]
It answers my question, however, I would argue that the UI is currently not self-explanatory in that sense. It very much looks like buttons you can manipulate. Maybe a plain list would be easier to understand in this context?

**Comment by SamuelWei** [comment]
<img width="514" alt="image" src="https://github.com/THM-Health/PILOS/assets/4281791/782039b6-0082-4b9a-b9c5-9ee32cdaf59b">
Alternative design idea
