### ISSUE TITLE
Import from greenlight

### ISSUE THREAD

**Issue by SamuelWei** [THM-Health/PILOS#117]
**Is your feature request related to a problem? Please describe.**
To allow an easy migration from one or multiple greenlight servers to this system, a migration script and tutorial would be very helpful.

**Describe the solution you'd like**
1. Dump postgres database of one or multiple greenlight servers
2. Call an artisan command e.g. php artisan import:greenlight db_dump.sql
3. Create (ldap) users
4. Create rooms with old urls if no name conflict, otherwise report
5. Create room memberships

Write nginx rule for old greenlight systems to redirect to new rooms: https://greenlight.bbb-domain.org/b/abc-vib-j8e -> https://pilos.bbb-domain.org/rooms/abc-vib-j8e

**Describe alternatives you've considered**
*none*

**Additional context**
*none*

**Comment by SamuelWei** [comment]
Replace

```
location /b {
  proxy_pass          http://127.0.0.1:5000;
  proxy_set_header    Host              $host;
  proxy_set_header    X-Forwarded-For   $proxy_add_x_forwarded_for;
  proxy_set_header    X-Forwarded-Proto $scheme;
  proxy_http_version  1.1;
}

location /b/cable {
  proxy_pass          http://127.0.0.1:5000;
  proxy_set_header    Host              $host;
  proxy_set_header    X-Forwarded-For   $proxy_add_x_forwarded_for;
  proxy_set_header    X-Forwarded-Proto $scheme;
  proxy_set_header    Upgrade           $http_upgrade;
  proxy_set_header    Connection        "Upgrade";
  proxy_http_version  1.1;
  proxy_read_timeout  6h;
  proxy_send_timeout  6h;
  client_body_timeout 6h;
  send_timeout        6h;
}

# Allow larger body size for uploading presentations
location ~ /preupload_presentation$ {
  client_max_body_size 30m;

  proxy_pass          http://127.0.0.1:5000;
  proxy_set_header    Host              $host;
  proxy_set_header    X-Forwarded-For   $proxy_add_x_forwarded_for;
  proxy_set_header    X-Forwarded-Proto $scheme;
  proxy_http_version  1.1;
}

# Only needed if using presentations and deployed at a relative root (ex "/b")
# If deploying at "/", delete the section below

location /rails/active_storage {
  return 301 /b$request_uri;
}
```

with

```
location /b {
   rewrite "^/b/([A-Za-z0-9]{3}-[A-Za-z0-9]{3}-[A-Za-z0-9]{3})$" https://DOMAIN.TLD/rooms/$1 redirect;
}
error_page  404  /moved.html;
```

add moved.html to webserver root, eg. /var/www/bigbluebutton-default

```html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
	<head>
		<title>Moved</title>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css" rel="stylesheet">
		<style>
			html {
				background: #06172A;
			}
			
			body {
				margin: 0;
				font-family: -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,"Noto Sans",sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol","Noto Color Emoji";
				font-size: 1rem;
				font-weight: 400;
				line-height: 1.5;
			}

			h3 {
				font-size: 1.75rem;
				margin-bottom: .5rem;
				font-weight: 500;
				line-height: 1.2;
			}
			
			#content {
				position: absolute;
				left: 50%;
				top: 50%;
				-webkit-transform: translate(-50%, -50%);
				transform: translate(-50%, -50%);
				text-align: center;
				color: #FFF;
				max-width: 700px;
			}
			
			.btn {
				color: #212529;
				background-color: #f8f9fa;
				border-color: #f8f9fa;
				display: block;
				font-weight: 400;
				color: #212529;
				text-align: center;
				vertical-align: middle;
				cursor: pointer;
				-webkit-user-select: none;
				-moz-user-select: none;
				-ms-user-select: none;
				user-select: none;
				border: 1px solid transparent;
				padding: .375rem .75rem;
				font-size: 1rem;
				line-height: 1.5;
				border-radius: .25rem;
				text-decoration: none;
				margin-top: 10px;
			}
			
			.btn:hover {
				color: #212529;
				background-color: #e2e6ea;
				border-color: #dae0e5;
			}
	</style>
	</head>
	<body>
		<div id="content">
			<i class="fas fa-directions" style="font-size: 5em;"></i>
			<h3>This service has been moved</h3>
			<i>The old room urls continue to work</i>
			<a href="https://DOMAIN.TLD" class="btn">Take me to the new service</a>
		</div>
	</body>
</html>
```

**Comment by dennis95stumm** [comment]
> Replace
> 
> ```
> location /b {
>   proxy_pass          http://127.0.0.1:5000;
>   proxy_set_header    Host              $host;
>   proxy_set_header    X-Forwarded-For   $proxy_add_x_forwarded_for;
>   proxy_set_header    X-Forwarded-Proto $scheme;
>   proxy_http_version  1.1;
> }
> 
> location /b/cable {
>   proxy_pass          http://127.0.0.1:5000;
>   proxy_set_header    Host              $host;
>   proxy_set_header    X-Forwarded-For   $proxy_add_x_forwarded_for;
>   proxy_set_header    X-Forwarded-Proto $scheme;
>   proxy_set_header    Upgrade           $http_upgrade;
>   proxy_set_header    Connection        "Upgrade";
>   proxy_http_version  1.1;
>   proxy_read_timeout  6h;
>   proxy_send_timeout  6h;
>   client_body_timeout 6h;
>   send_timeout        6h;
> }
> 
> # Allow larger body size for uploading presentations
> location ~ /preupload_presentation$ {
>   client_max_body_size 30m;
> 
>   proxy_pass          http://127.0.0.1:5000;
>   proxy_set_header    Host              $host;
>   proxy_set_header    X-Forwarded-For   $proxy_add_x_forwarded_for;
>   proxy_set_header    X-Forwarded-Proto $scheme;
>   proxy_http_version  1.1;
> }
> 
> # Only needed if using presentations and deployed at a relative root (ex "/b")
> # If deploying at "/", delete the section below
> 
> location /rails/active_storage {
>   return 301 /b$request_uri;
> }
> ```
> 
> with
> 
> ```
> location /b {
>    rewrite "^/b/([A-Za-z0-9]{3}-[A-Za-z0-9]{3}-[A-Za-z0-9]{3})$" https://DOMAIN.TLD/rooms/$1 redirect;
> }
> error_page  404  /moved.html;
> ```
> 
> add moved.html to webserver root, eg. /var/www/bigbluebutton-default
> 
> ```
> <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
> <html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
> 	<head>
> 		<title>Moved</title>
> 		<meta charset="utf-8">
> 		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
> 		<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css" rel="stylesheet">
> 		<style>
> 			html {
> 				background: #06172A;
> 			}
> 			
> 			body {
> 				margin: 0;
> 				font-family: -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,"Noto Sans",sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol","Noto Color Emoji";
> 				font-size: 1rem;
> 				font-weight: 400;
> 				line-height: 1.5;
> 			}
> 
> 			h3 {
> 				font-size: 1.75rem;
> 				margin-bottom: .5rem;
> 				font-weight: 500;
> 				line-height: 1.2;
> 			}
> 			
> 			#content {
> 				position: absolute;
> 				left: 50%;
> 				top: 50%;
> 				-webkit-transform: translate(-50%, -50%);
> 				transform: translate(-50%, -50%);
> 				text-align: center;
> 				color: #FFF;
> 				max-width: 700px;
> 			}
> 			
> 			.btn {
> 				color: #212529;
> 				background-color: #f8f9fa;
> 				border-color: #f8f9fa;
> 				display: block;
> 				font-weight: 400;
> 				color: #212529;
> 				text-align: center;
> 				vertical-align: middle;
> 				cursor: pointer;
> 				-webkit-user-select: none;
> 				-moz-user-select: none;
> 				-ms-user-select: none;
> 				user-select: none;
> 				border: 1px solid transparent;
> 				padding: .375rem .75rem;
> 				font-size: 1rem;
> 				line-height: 1.5;
> 				border-radius: .25rem;
> 				text-decoration: none;
> 				margin-top: 10px;
> 			}
> 			
> 			.btn:hover {
> 				color: #212529;
> 				background-color: #e2e6ea;
> 				border-color: #dae0e5;
> 			}
> 	</style>
> 	</head>
> 	<body>
> 		<div id="content">
> 			<i class="fas fa-directions" style="font-size: 5em;"></i>
> 			<h3>This service has been moved</h3>
> 			<i>The old room urls continue to work</i>
> 			<a href="https://DOMAIN.TLD" class="btn">Take me to the new service</a>
> 		</div>
> 	</body>
> </html>
> ```

@SamuelWei Could we add a command for this or put it into a documentation?

**Comment by SamuelWei** [comment]
We don't need this anymore, see #142
