### ISSUE TITLE
Error on empty access code

### ISSUE THREAD

**Issue by robyhartonodev** [THM-Health/PILOS#136]
**Describe the bug**
Secured room with access code redirect to login triggers error, if input field for the code is empty, when the user is on the logged out state.

**To Reproduce**
1. Put the link of the room that secured with access code in the browser.
2. Make sure the user is logged out.
3. Let the input field for access code empty.
4. Click login button.
5. Unknown flash error message triggered.

**Expected behavior**
User should be redirected to login page, instead of flash unknown error message without redirect or access code invalid error should be triggered.

**Screenshots**
![image](https://user-images.githubusercontent.com/17837057/116851806-641da880-abf3-11eb-8f6d-45f1eb19f0fd.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home 19042.928
 - Browser Google Chrome
 - Version  90.0.4430.93

**Additional context**

**Comment by SamuelWei** [comment]
Thank you for your report. I can confirm the issue.
