### ISSUE TITLE
Missing DB tables after fresh install of 4.0.0-RC.2

### ISSUE THREAD

**Issue by tibroc** [THM-Health/PILOS#1363]
**Describe the bug**
When installing [4.0.0-RC.2](https://github.com/THM-Health/PILOS/releases/tag/v4.0.0-RC.2), the database is not initialized. This is either a bug in the process for the first start of the system or missing in the installation instructions of the docs. If it is the latter I can provide a PR.

**To Reproduce**
1. Install a fresh PILOS [4.0.0-RC.2](https://github.com/THM-Health/PILOS/releases/tag/v4.0.0-RC.2)
2. See `docker compose logs -f` to find db-related error messages where tables are missing 
3. Run `docker compose exec app pilos-cli migrate --seed`
4. See the errors disappear

**Expected behavior**
Seeding the DB should either be part of the initial start process or be mentioned in the installation instructions.

**Comment by SamuelWei** [comment]
https://github.com/user-attachments/assets/384a7800-b854-4c99-bb49-8c518699b30d
