### ISSUE TITLE
Missing slash in join room url in bbb room

### ISSUE THREAD

**Issue by ashishkpaul** [THM-Health/PILOS#153]
Hello sir, Great Work. I tried and found, its showing wrong invite url inside the bbb chat dock (back slash missing after the domain name). its showing invite url http://ldap.vijlect.xyzrooms/hal-pce-u5r instead of http://ldap.vijlect.xyz/rooms/hal-pce-u5r

**Comment by SamuelWei** [comment]
Hello @ashishkpaul thank you for your report. We will fix it asap. A workaround would be to add a slash to the APP_URL in your .env file

**Comment by ashishkpaul** [comment]
:+1:  Thanks

**Comment by SamuelWei** [comment]
@ashishkpaul The bug is fixed in https://github.com/THM-Health/PILOS/releases/tag/v1.4.1
