### ISSUE TITLE
User Rights: MODERATOR  vs CO-OWNER

### ISSUE THREAD

**Issue by ashishkpaul** [THM-Health/PILOS#160]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**
As I think sir co-owner should not have rights to **Start** and **End** the meeting. It should be only moderator rights

**Additional context**

**Comment by SamuelWei** [comment]
Hello ashishkpaul,

the permission hierarchy is as follows:

guest > participant > member > moderator > co-owner > owner > admin 

The moderator's permissions are limited to the BBB meeting room. The co-owner has the same permission as the owner except the co-owner cannot delete the room. In comparison to the moderator the co-owner can also mange the users, edit files and the room settings.

**Comment by ashishkpaul** [comment]
Thanks for the explanation
