### ISSUE TITLE
user role filter

### ISSUE THREAD

**Issue by ashishkpaul** [THM-Health/PILOS#161]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**
it would be better if admin can filter a user by role

**Additional context**
![Screenshot_2021-08-09_17-39-22](https://user-images.githubusercontent.com/16308863/128706396-e48e4980-27db-4452-9156-51592cfe3336.png)

**Comment by SamuelWei** [comment]
The user can have multiple roles, thats why this feature is a bit complicated, but we will think about it.
