### ISSUE TITLE
Undefined Invite URL

### ISSUE THREAD

**Issue by ashishkpaul** [THM-Health/PILOS#188]
**Describe the bug**
Hello sir, Access for participants giving the undefined link

**To Reproduce**
1. Go to 'My Room'
2. Click on 'Create a New Room or Already Created Room'
3. Scroll down to 'Access for participants'
Join 'Live-Saa9vi' with PILOS
Link: undefined/rooms/bvu-qyi-zyx
Access code: ZZZ-YYY-XXX

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by SamuelWei** [comment]
Hi @ashishkpaul,

could you please check if you have MIX_FRONTEND_BASE_URL set in your .env file (https://github.com/THM-Health/PILOS/blob/master/.env.example#L97)
After adding it, please re-run: npm run prod

If that fixes your problem, you can close the issue.
