### ISSUE TITLE
Enter in room

### ISSUE THREAD

**Issue by squid46** [THM-Health/PILOS#215]
Vor- und Nachname
Александър
Name enthält nicht erlaubte Zeichen

Александър auf bulgarisch UTF8.

**Comment by SamuelWei** [comment]
Hello,

we currently only support a limited range of chars, see: https://github.com/THM-Health/PILOS/blob/master/app/Rules/ValidName.php#L9

**Comment by squid46** [comment]
In the username, room, etc. support, but when you enter a room do not?

**Comment by SamuelWei** [comment]
The name of the registered user are either from a trusted source like LDAP or created by the admin.
By restricting the valid chars of the guests name, we want to enforce valid names (even if this is no guarantee, doesn't prevent names like: abc and gdfg) and prevent meaningless names like §$%fg, d7434, etc.

Filtering the guest name is also an additional precaution against possible XSS in BBB, etc.

**Comment by squid46** [comment]
Can I add to it like this?
A-Za-zА-Яа-яàáâäãåąčćęèéêëėįìíîïłńòóôöõøùúûüųūÿýżźñçšžÀÁÂÄÃÅĄĆČĖĘÈÉÊËÌÍÎÏĮŁŃÒÓÔÖÕØÙÚÛÜŲŪŸÝŻŹÑßÇŒÆŠŽ∂ð

**Comment by SamuelWei** [comment]
Yes, just open a PR

**Comment by SamuelWei** [comment]
Stale
