### ISSUE TITLE
Label in room restrictions section broken

### ISSUE THREAD

**Issue by tibroc** [THM-Health/PILOS#263]
**Describe the bug**
On the [demo page](https://pilos.coding-space.de) there is a broken label in the "Restrictions" section of the room settings (disable privat chat):
![image](https://user-images.githubusercontent.com/39943803/187865356-af83e209-a2d4-4d24-b14e-69a050e3d267.png)

**To Reproduce**
1. Go to the room settings on the demo page 

**Expected behavior**
A label like "Disable private chat" instead of the current label.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser FF
 - Version 104

**Comment by SamuelWei** [comment]
Already fixed in 84affcc
