### ISSUE TITLE
Implement load balancer

### ISSUE THREAD

**Issue by SamuelWei** [THM-Health/PILOS#29]
**Is your feature request related to a problem? Please describe.**
The system should use a load balancer for creating new meetings and display server status.
Similar to https://github.com/blindsidenetworks/scalelite 

**Describe the solution you'd like**
Use data collected by #64 for each new meeting to calculate the server load based on amount of meetings and estimated network traffic, cpu usage, etc. and use a server specific multiplicator to handle different hardware. 

Use the server with the lowest load of the server pool (#30) the room has selected and try to create meeting. If not possible, try next less loaded server. If all servers are not available throw error. 

**Describe alternatives you've considered**
Just use https://github.com/blindsidenetworks/scalelite

**Comment by dennis95stumm** [comment]
@SamuelWei isn't this already implemented in the RoomController?

**Comment by SamuelWei** [comment]
Yes, it was implemented with #88
