### ISSUE TITLE
When I try to upload a pdf or ppt file larger than 1Mb, it doesn't allow me to upload it.

### ISSUE THREAD

**Issue by jorgelondo** [THM-Health/PILOS#347]
Something similar happens to me in the PILOS demo than in Greenlight when I try to upload a pdf or ppt file larger than 1Mb, it doesn't allow me to upload it.

![pilos-big-upload](https://github.com/THM-Health/PILOS/assets/672505/ee4f11fb-b1ad-4c74-b549-00d531ffd2d1)

**Comment by SamuelWei** [comment]
Hi @jorgelondo,

please check your upload limits set in the reverse proxy (nginx or apache).

Greetings
Samuel

**Comment by SamuelWei** [comment]
@jorgelondo Did this fix your issue?

**Comment by jorgelondo** [comment]
Hi @SamuelWei , I couldn't, I don't know if it's because it's installed in an AWS instance.
It didn't work for me with Greenlight either.
Thanks

**Comment by SamuelWei** [comment]
Please write me an email so we can have private chat some time soon: https://www.thm.de/ges/en/faculty/profile/team/samuel-weirich-2
