### ISSUE TITLE
Rebuild dashboard / room search

### ISSUE THREAD

**Issue by Sabr1n4W** [THM-Health/PILOS#372]
**Is your feature request related to a problem? Please describe.**
The rooms are always sorted by their name in alphabetical order. Because of this it can be difficult to find a specific room quickly without using the search.

**Describe the solution you'd like**
Add multiple sorting options to make it easier to find a room without using the search.
examples:

- number of room members?
- currently running?
- last started?
- name (alphabetical order)
- room owner?
- ...

**Describe alternatives you've considered**
none

**Additional context**

**current sorting:**
![Screenshot (31)](https://github.com/THM-Health/PILOS/assets/119059706/fa76ed7c-dfb8-4230-acb0-ce56e23de453)

**potential new button and dropdown**
![Screenshot (34)](https://github.com/THM-Health/PILOS/assets/119059706/acb1683f-e775-4df2-9517-29cdb286cd0a)

**Comment by SamuelWei** [comment]
![image](https://github.com/THM-Health/PILOS/assets/4281791/8ff11203-a53d-43d8-b20f-9fe7b2ce4822)

Full width search
Dropdown fields for room type and sort order

**Comment by SamuelWei** [comment]
![image](https://github.com/THM-Health/PILOS/assets/4281791/b3a86897-c7b8-4942-b47d-c94cabf98f22)

**Comment by SamuelWei** [comment]
![Folie1](https://github.com/THM-Health/PILOS/assets/4281791/dcf0605d-3718-4fc7-84be-2304f2b70013)
![Folie2](https://github.com/THM-Health/PILOS/assets/4281791/19b4629a-8b68-4f1c-b958-28a519bd8cf5)
![Folie3](https://github.com/THM-Health/PILOS/assets/4281791/853c9d95-c11b-4cde-b30e-06296569d4e0)
