### ISSUE TITLE
Add command to test email configuration

### ISSUE THREAD

**Issue by SamuelWei** [THM-Health/PILOS#530]
**Is your feature request related to a problem? Please describe.**
Currently there is no easy way to test if the email configuration is working

**Describe the solution you'd like**
Create an easy to use artisan command to test the email configuration by sending a test mail to a given email address

**Comment by gustavogabaldon** [comment]
hello, id like to contribute to this issue. can you provide the path to file?

**Comment by SamuelWei** [comment]
What path are you looking w?
