### ISSUE TITLE
Login error in dev environment 

### ISSUE THREAD

**Issue by dennis531** [THM-Health/PILOS#552]
**Description**
After I set up the development environment, I can not log in with my created admin account. When I tried to log in, I received the following error message: `Session store not set on request`.

I followed the instructions in https://github.com/THM-Health/PILOS/blob/036a29dbac3e97e9213bf3970aa1df3804e9667c/CONTRIBUTING.md without SSL.

**To Reproduce**
1. Go to 'login'
2. Fill your credentials
3. Click on button 'login'
5. See error

**Expected behavior**
I should be logged in.

**Screenshots**
![image](https://github.com/THM-Health/PILOS/assets/44410838/b3dafc9d-9f6f-4188-b7cf-1149a4b05bc1)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.3 LTS
 - Browser Firefox and Chrome
 - Version master (036a29dbac3e97e9213bf3970aa1df3804e9667c)

**Quick Fix**
I could fix this problem by adding the class `\Illuminate\Session\Middleware\StartSession::class` to the variable `$middleware` in https://github.com/THM-Health/PILOS/blob/036a29dbac3e97e9213bf3970aa1df3804e9667c/app/Http/Kernel.php .

**Comment by SamuelWei** [comment]
Please check your [APP_URL](https://github.com/THM-Health/PILOS/blob/master/.env.example#L6), and if you have a reverse proxy check your [TRUSTED_PROXIES settings](TRUSTED_PROXIES) and [webserver config](https://github.com/THM-Health/PILOS/blob/master/docs/INSTALL.md#webserver)

If you make any changes to the .env you need to restart the container (if you use docker compose directly); if you use sail as documented in the [CONTRIBUTING.md](https://github.com/THM-Health/PILOS/blob/master/CONTRIBUTING.md) a restart is not nessesarry

**Comment by dennis531** [comment]
Thanks for the hint about the `APP_URL`. I had set the port `APP_PORT=8081` but forgot to add the port to `APP_URL`. After this change the problem was solved.

My working settings:
```
# API Server URL
APP_URL=http://localhost:8081
APP_PORT=8081
```
