### ISSUE TITLE
Custom Defaults for Room Types

### ISSUE THREAD

**Issue by tibroc** [THM-Health/PILOS#559]
**Is your feature request related to a problem? Please describe.**
For different types of video conferences (e.g. meetings, lectures) you might want to have custom default room settings. E.g. in a meeting you might want to start with a grid layout and minimized whiteboard, whereas in a lecture you would want to start with a focus on the presentation.

**Describe the solution you'd like**
PILOS already offers room types but not yet their customization. It would be nice for the admin to be able to set at least the default layout of the room type. So I would start with adding something like a "custom create parameter" field in the room types menu that lets admins customize the create API-call from PILOS to BBB.

**Describe alternatives you've considered**
Maybe a UI that allows admins to switch these settings on/off is also possible, but since these values should be only visible to admins and those should be familiar with configuring BBB, it seems to be unecessary overhead. Plus you would need to track BBB versions and which parameters are possible for each BBB-API version, which would mean a more complex implementation and more maintanence work in the future.

**Additional context**
This is probably a subtask of https://github.com/THM-Health/PILOS/issues/75.

**Comment by tibroc** [comment]
@dennis531

**Comment by dennis531** [comment]
Custom create parameters in room type settings:
![image](https://github.com/THM-Health/PILOS/assets/44410838/ff090d20-6087-44b4-8cd8-8aff1a39cca7)

In room settings, @tibroc and I suggest that matching custom parameters should be preset when changing room types. Thereby, it should be possible for the user to adjust the corresponding room settings.

**Comment by SamuelWei** [comment]
Should it be possible to the user to adjust the create parameters in his room settings, or is it something only the admins can do?

**Comment by dennis531** [comment]
> Should it be possible for the user to adjust the create parameters in his room settings, or is it something only the admins can do?

The create parameters should only be adjustable in the admin room type settings. Only room settings that match create custom parameters will be adjusted when setting the room type. In this case, the values from the custom parameters should be preset, but remain customizable in the room settings. The remaining parameters would remain hidden from the user in the room settings.

**Comment by SamuelWei** [comment]
We also thought about adding all settings from the room settings to the room type via a UI, allowing admins to set the default and enforce some settings (eg. prohibit the attendace recording). M

**Comment by dennis531** [comment]
> We also thought about adding all settings from the room settings to the room type settings via a UI in a tabular form, allowing admins to set the default and enforce some settings (eg. prohibit the attendace recording).

If I see it correctly, the changes proposed in this issue should not conflict with these.
