### ISSUE TITLE
User preferences

### ISSUE THREAD

**Issue by SamuelWei** [THM-Health/PILOS#67]
**Is your feature request related to a problem? Please describe.**
Like in greenlight, a user preference page would be great.

**Describe the solution you'd like**
On the page some user attributes can be displayed and edited.
- The username should not be changable.
- The attributes name and email should not be changable for ldap users.
- The user can choose to skip the echo test, default is false (https://docs.bigbluebutton.org/2.2/customize.html#passing-custom-parameters-to-the-client-on-join)

**Describe alternatives you've considered**
*none*

**Additional context**

**Comment by dennis95stumm** [comment]
Everything already exists except the skip echo test option. @SamuelWei Should only this option be added or should also other option added?

**Comment by SamuelWei** [comment]
The only thing I know about right now is the echo test.
