### ISSUE TITLE
Restructure room settings page

### ISSUE THREAD

**Issue by SamuelWei** [THM-Health/PILOS#695]
**Is your feature request related to a problem? Please describe.**
As PILOS becomes more and more complex, the page with the room settings is becoming increasingly confusing and difficult to maintain.

**Describe the solution you'd like**
Reorganize how the settings are displayed.

**Current overview**
![screencapture-pilos-thm-de-rooms-bf0-gbg-kwd-2023-11-20-20_37_18](https://github.com/THM-Health/PILOS/assets/4281791/56429771-cd3b-40f3-84ac-8a2e91b1b3c5)

**Mockup**
![screencapture-localhost-rooms-59l-jdh-hgy-2023-11-20-20_35_45](https://github.com/THM-Health/PILOS/assets/4281791/6ef223c7-4380-4dcc-a55c-1788e412d895)

**Comment by tibroc** [comment]
I agree that the room settings page is becoming overwhelming. However, I am not sure if a restructuring is enough to make it usable. My main question would be, if it is actually necessary to expose the complex configuration options that BBB offers to *every* user. Maybe it would be better to make all of these options only accessible to site admins and offer normal users only predefined presets (as in "room types" e.g.).

**Comment by SamuelWei** [comment]
> I agree that the room settings page is becoming overwhelming. However, I am not sure if a restructuring is enough to make it usable. My main question would be, if it is actually necessary to expose the complex configuration options that BBB offers to _every_ user. Maybe it would be better to make all of these options only accessible to site admins and offer normal users only predefined presets (as in "room types" e.g.).

Years back we also discussed an easy and expert mode, hiding same settings.

What options whould you move from the room settings to a global setting in the room type?

**Comment by tibroc** [comment]
Access control like who can enter and how, should be configurable by the user. All the rest would imo better be preconfigured. Something like (not really thought through):
* you want a business meeting so you choose room type "meeting" that comes with activated cameras and microfones
* you want a big lecture so you choose "lecture" which deactivates cameras for all users except the moderator
* you want an exam so you choose that type which deactives private chat etc.…

**Comment by JeanPluzo** [comment]
Hi,

I agree with @tibroc. I think admins are there for a reason: they should know better than users, hence they have more responsibility as well as time to explore the "advanced" features. And you _will_ have at least one admin to "govern" a PILOS instance, even if it's not really an admin but an experienced user. 
Users should be left with simpler choices or they could also become overwhelmed. I've seen this happen even in GLv2 with some of my users.
Here's another idea: what about using some predefined settings for each room, and only when an admin wishes to change those settings, a drop-down menu appears where all settings are described/included?
For example, you could have "Webcam deaktivieren" and "Mikrofon deaktivieren" as predefined choices already selected. But if more detailed restrictions are needed, the admin/user has to click on the drop-down menu "Weitere Berechtigungen einschrenken". There and only there could the admin/user set other restrictions.
This should doable with Vue.js, right? 
Just an idea.

Regards,
J.

**Comment by SamuelWei** [comment]
- Add all room settings that can have a default value (all but text inputs) to the room types.
- Allow admins to set a default for all these values, as well as a checkbox to enforce this value
- Show these settings as default settings or enforced settings on selecting / changing room type
- Add expert mode to room settings
- If user has expert mode enabled, he can see all settings and change all not-enfored settings
- If a user changes the room type with export mode enabled, ask to apply default settings
- By default only show: Room type, Room name, Access code, Guest access (first row in the mockup, all else is "expert")
