### ISSUE TITLE
Personalised room links

### ISSUE THREAD

**Issue by SamuelWei** [THM-Health/PILOS#72]
**Is your feature request related to a problem? Please describe.**
It should be possible to create a personalised room link for a meeting. This is for those cases where the general allow guest rule it to broad, but it would also make no sence to create a new user account for this person.

**Describe the solution you'd like**
Add a new section to the room overview, next to members and files. or implement feature into the members section.

Clicking on a create button opens a modal, asking for the persons name and role (participant or moderator). Once completed, a link should be shown. All personalised room links should be shown in a table, so the name and role can be edited and removed. The actual link could be hidden behind a button to make the table more clean.

If someone is using this link, they should not be required to enter a room acccess code. They can't modify their name, as it is set by the data in the database.

**UI ideas**
![persroomlinks](https://user-images.githubusercontent.com/4281791/120449664-ef739080-c38f-11eb-8e24-d6358a516a37.PNG)
![image](https://user-images.githubusercontent.com/4281791/120450494-c7d0f800-c390-11eb-870c-b8bf17fe2086.png)

**Comment by dennis95stumm** [comment]
@SamuelWei Should the room access code really be not necessary? For logged in users the access code is also necssray!
