### ISSUE TITLE
Room type presets

### ISSUE THREAD

**Issue by SamuelWei** [THM-Health/PILOS#75]
**Is your feature request related to a problem? Please describe.**
In  #62 the basis room attributes are introduced. In addition to the already existing attributes each RoomType should have some more attributes that effect the room settings for all rooms with this type.

**Describe the solution you'd like**
A RoomTypeSettings Model should be created.
For each RoomType the RoomTypeSettings should be editable.
Each RoomTypeSetting (predefined list via seeder) can be set, accordingly to its content type and enforced.
Enforced means that the user cannot change the setting in the room settings. If the RoomType is changed, apply the enforced settings: overwrite and lock.
E.g. RoomType "Private Meeting" -> enforce 'allow guests' disabled and require access code. 
If a setting is not enforced the settings are applied once on creation of new meetings with this type.

**Describe alternatives you've considered**

--

**Additional context**
Future ideas

- [x] Add server clusters for each room type and enforce selection (solved in #99)
- [x] Grant access to room types for some groups, e.g. Students can only create 'small group' meetings, limited in the duration, max. participants and server pool (see #98)

**Comment by dennis95stumm** [comment]
My proposal:
![Untitled Diagram-Page-1](https://user-images.githubusercontent.com/6422711/110019364-a9734600-7d28-11eb-9d60-9d73c2850f3d.png)
![Untitled Diagram-Page-2](https://user-images.githubusercontent.com/6422711/110019368-aaa47300-7d28-11eb-830d-d729ddc10e86.png)

**Comment by dennis95stumm** [comment]
For this and for ticket #98
