### ISSUE TITLE
Add more managable application settings

### ISSUE THREAD

**Issue by dsst95** [THM-Health/PILOS#78]
**Is your feature request related to a problem? Please describe.**
Currently only a part of the application settings is manageable.

**Describe the solution you'd like**
Add more settings to the application manage view. For example:

- [ ] Mail config?
- [ ] Ldap config? (*may not work if you must login!*)
- [ ] Ldap role mapping
- [ ] Default locale
- [ ] Selectable locales

**Comment by SamuelWei** [comment]
Add system wide default presentation
