### ISSUE TITLE
Improve github action speed

### ISSUE THREAD

**Issue by SamuelWei** [THM-Health/PILOS#82]
**Is your feature request related to a problem? Please describe.**
Currently each run takes about 6 minutes, that is quite long - bad for developers and github ressources. The speed should be improved.

**Describe the solution you'd like**
Adding caching for unchanged composer and node packages should improve the performance a bit.

**Comment by dennis95stumm** [comment]
CI now fails due to caching errors

**Comment by dennis95stumm** [comment]
Hopefully fixed with b0cf612774502e7bfba96f366d1471abda2fdd91 and 42af9654ffc3e92da4286766cddcbd25f036baa0
