### ISSUE TITLE
Maintenance/Info banner

### ISSUE THREAD

**Issue by SamuelWei** [THM-Health/PILOS#89]
**Is your feature request related to a problem? Please describe.**
Like in greenlight it would be great to have a banner for maintenance or other information.

**Describe the solution you'd like**
Adding application settings for info banner: enabled/disabled, color/bootstrap variant, message (html code)

**Describe alternatives you've considered**
Having a html code message can be dangerous. To allow some basic features, adding an icon, heading, message text and link (each optional) could be an alternative. 

**Additional context**
Example screenshot
![image](https://user-images.githubusercontent.com/4281791/102392947-0720ad80-3fd8-11eb-9ae8-9f3c97c7adaa.png)

**Comment by SamuelWei** [comment]
Similar to #78

**Comment by dennis95stumm** [comment]
@SamuelWei Should this be a banner or a flash message?

**Comment by SamuelWei** [comment]
Just a banner that is always present
